import { useEffect, useState } from "react";
import { ArrowClockwise, CaretDown, CaretUp, Pause, Play, Plus } from "@phosphor-icons/react";
import type { AnalysisQueueStatus, AppSettings, Category, LibraryImage, LibraryStats } from "../../shared/types";
import { TopBar } from "../components/TopBar";

type Tab = "library" | "categories" | "privacy" | "pet" | "appearance";

export function SettingsPage({ onMenu, settings, onSettings, refreshLibrary }: { onMenu(): void; settings: AppSettings; onSettings(value: AppSettings): void; refreshLibrary(): Promise<void> }) {
  const [tab, setTab] = useState<Tab>("library");
  const [categories, setCategories] = useState<Category[]>([]);
  const [trash, setTrash] = useState<LibraryImage[]>([]);
  const [stats, setStats] = useState<LibraryStats | null>(null);
  const [queueStatus, setQueueStatus] = useState<AnalysisQueueStatus | null>(null);
  const [apiKey, setApiKey] = useState("");
  const [keyExists, setKeyExists] = useState(false);
  const [status, setStatus] = useState("");
  const reload = async () => { const [nextCategories, nextTrash, nextKeyExists, nextStats, nextQueueStatus] = await Promise.all([window.appApi.categories(), window.appApi.listTrash(), window.appApi.hasApiKey(), window.appApi.getStats(), window.appApi.getAnalysisQueueStatus()]); setCategories(nextCategories); setTrash(nextTrash); setKeyExists(nextKeyExists); setStats(nextStats); setQueueStatus(nextQueueStatus); };
  useEffect(() => { void reload(); return window.appApi.onLibraryChanged(() => { void reload(); }); }, []);
  useEffect(() => { if (!queueStatus || queueStatus.pending + queueStatus.analyzing === 0) return; const timer = setInterval(() => { void reload(); }, 2_000); return () => clearInterval(timer); }, [queueStatus?.pending, queueStatus?.analyzing]);
  const save = async (patch: Partial<AppSettings>) => { const next = { ...settings, ...patch }; onSettings(next); await window.appApi.saveSettings(next); };
  const tabs: Array<[Tab, string]> = [["library", "图库"], ["categories", "分类"], ["privacy", "Gemini 与隐私"], ["pet", "桌宠"], ["appearance", "外观"]];

  return <main className="settings-page">
    <TopBar onMenu={onMenu} settings={settings} onSettings={onSettings}><strong>数据与设置</strong></TopBar>
    <nav className="settings-tabs">{tabs.map(([value, label]) => <button key={value} className={tab === value ? "active" : ""} onClick={() => setTab(value)}>{label}</button>)}</nav>
    <section className="settings-content">
      {tab === "library" && <>
        <h1>本地图库</h1>
        {stats && <div className="stats-grid"><div><strong>{stats.imageCount}</strong><span>图片</span></div><div><strong>{((stats.originalBytes + stats.thumbnailBytes + stats.databaseBytes) / 1048576).toFixed(1)} MB</strong><span>本地占用</span></div><div><strong>{stats.completed}</strong><span>已分类</span></div><div><strong>{stats.failed}</strong><span>分析失败</span></div></div>}
        {queueStatus && <div className="setting-card analysis-queue-card">
          <header><div><h2>自动分析</h2><p>{queueStatus.paused ? queueStatus.pauseReason === "daily-quota" ? `今日额度已用完，将于 ${queueStatus.pauseUntil ? new Date(queueStatus.pauseUntil).toLocaleString() : "额度重置后"} 继续` : "队列已手动暂停" : queueStatus.analyzing > 0 ? "正在分析图片，每次请求至少间隔 30 秒" : queueStatus.pending > 0 ? "图片正在排队，应用会自动继续" : "队列当前没有待处理图片"}</p></div><span className={`analysis-queue-state ${queueStatus.paused ? "paused" : queueStatus.analyzing > 0 || queueStatus.pending > 0 ? "working" : queueStatus.failed > 0 ? "failed" : "idle"}`}>{queueStatus.paused ? "已暂停" : queueStatus.analyzing > 0 ? "分析中" : queueStatus.pending > 0 ? "等待中" : queueStatus.failed > 0 ? `处理结束 · ${queueStatus.failed} 张失败` : "已完成"}</span></header>
          <div className="analysis-queue-counts"><span><strong>{queueStatus.pending}</strong>等待</span><span><strong>{queueStatus.analyzing}</strong>分析中</span><span><strong>{queueStatus.failed}</strong>失败</span></div>
          <div className="button-row">{queueStatus.failed > 0 && <button onClick={() => { sessionStorage.setItem("library-filter-request", "failed"); location.hash = "#/"; }}>查看失败图片</button>}<button disabled={queueStatus.failed === 0} onClick={async () => { const count = await window.appApi.retryFailedAnalyses(); setStatus(count ? `已将 ${count} 张失败图片重新加入队列` : "没有需要重试的图片"); await reload(); }}><ArrowClockwise size={17}/>重试全部失败</button>{queueStatus.paused ? <button className="primary" onClick={async () => { setQueueStatus(await window.appApi.resumeAnalyses()); setStatus("自动分析已继续"); }}><Play size={17}/>继续分析</button> : <button onClick={async () => { setQueueStatus(await window.appApi.pauseAnalyses()); setStatus("自动分析将在当前请求结束后暂停"); }}><Pause size={17}/>暂停分析</button>}</div>
        </div>}
        <div className="setting-card"><h2>备份与恢复</h2><p>备份包含数据库、原图和缩略图，不包含 Gemini API 密钥。恢复前会自动备份当前图库。</p><div className="button-row"><button className="primary" onClick={async () => { const result = await window.appApi.createBackup(); setStatus(result ? "备份创建成功" : "已取消"); }}>创建备份</button><button onClick={async () => { const result = await window.appApi.validateBackup(); setStatus(result ? "备份校验通过" : "已取消"); }}>校验备份</button><button onClick={async () => { const result = await window.appApi.restoreBackup(); if (result) { await reload(); await refreshLibrary(); setStatus("恢复成功，请重新配置 Gemini 密钥"); } }}>恢复备份</button><button onClick={async () => { setStatus("正在重建缩略图…"); await window.appApi.rebuildThumbnails(); await reload(); setStatus("缩略图重建完成"); }}>重建缩略图</button></div></div>
        <div className="setting-card"><h2>最近删除</h2>{trash.length ? trash.map((image) => <div className="trash-row" key={image.id}><span>{image.originalName}</span><div className="button-row"><button onClick={async () => { await window.appApi.restoreImage(image.id); await reload(); await refreshLibrary(); }}>恢复</button><button className="danger" onClick={async () => { if (confirm("永久删除后无法恢复，确定继续吗？")) { await window.appApi.permanentlyDeleteImage(image.id); await reload(); } }}>永久删除</button></div></div>) : <p className="muted">最近删除中没有图片。</p>}</div>
      </>}

      {tab === "categories" && <><h1>主分类</h1><p className="muted">每张图片有一个主分类，并可拥有多个设计术语。删除分类时会先迁移其中图片。</p><div className="category-list">{categories.map((category, index) => <div key={category.id}><input type="color" value={category.color} onChange={async (event) => { await window.appApi.updateCategory(category.id, { color: event.target.value }); await reload(); }}/><input defaultValue={category.name} onBlur={async (event) => { if (event.target.value.trim() !== category.name) { await window.appApi.updateCategory(category.id, { name: event.target.value.trim() }); await reload(); } }}/><div className="button-row"><button aria-label="上移分类" disabled={index === 0} onClick={async () => { const previous = categories[index - 1]; await Promise.all([window.appApi.updateCategory(category.id, { sortOrder: previous.sortOrder }), window.appApi.updateCategory(previous.id, { sortOrder: category.sortOrder })]); await reload(); }}><CaretUp size={16}/></button><button aria-label="下移分类" disabled={index === categories.length - 1} onClick={async () => { const next = categories[index + 1]; await Promise.all([window.appApi.updateCategory(category.id, { sortOrder: next.sortOrder }), window.appApi.updateCategory(next.id, { sortOrder: category.sortOrder })]); await reload(); }}><CaretDown size={16}/></button><button className="danger" disabled={categories.length < 2} onClick={async () => { const target = categories.find((item) => item.name === "其他" && item.id !== category.id) ?? categories.find((item) => item.id !== category.id); if (target && confirm(`删除“${category.name}”并把图片迁移到“${target.name}”？`)) { await window.appApi.deleteCategory(category.id, target.id); await reload(); await refreshLibrary(); } }}>删除</button></div></div>)}</div><button className="text-button" onClick={async () => { await window.appApi.createCategory(`新分类 ${categories.length + 1}`, "#0071E3"); await reload(); }}><Plus size={16}/>新建分类</button></>}

      {tab === "privacy" && <><h1>Gemini 与隐私</h1><div className="privacy-note">启用 AI 时，只有当前需要分析的图片会发送给 Gemini。图库、笔记和相关推荐不会上传。</div><div className="setting-card"><label>Gemini API 密钥<input type="password" value={apiKey} onChange={(event) => setApiKey(event.target.value)} placeholder={keyExists ? "已安全保存，输入新值可替换" : "输入 API 密钥"}/></label><div className="button-row"><button onClick={async () => { await window.appApi.setApiKey(apiKey); setApiKey(""); setKeyExists(true); setStatus("密钥已使用 Windows 本地加密保存"); }}>安全保存</button><button disabled={!keyExists} onClick={async () => { setStatus("正在测试连接…"); try { await window.appApi.testGemini(); setStatus("Gemini 连接正常"); } catch (error) { setStatus(error instanceof Error ? error.message : "连接失败"); } }}>测试连接</button></div></div><div className="setting-card"><h2>图片分析方式</h2>{([["automatic", "导入后自动分析"], ["confirm", "每次发送前确认"], ["off", "关闭 AI，仅本地保存"]] as const).map(([value, label]) => <label className="radio-row" key={value}><input type="radio" checked={settings.aiMode === value} onChange={() => save({ aiMode: value })}/>{label}</label>)}</div></>}

      {tab === "pet" && <><h1>桌宠</h1><div className="setting-card"><label className="toggle-row"><span>始终置顶</span><input type="checkbox" checked={settings.petAlwaysOnTop} onChange={(event) => save({ petAlwaysOnTop: event.target.checked })}/></label><label className="toggle-row"><span>提示音</span><input type="checkbox" checked={settings.petSound} onChange={(event) => save({ petSound: event.target.checked })}/></label><label>提示音量<input type="range" min="0" max="1" step="0.05" value={settings.petVolume} onChange={(event) => save({ petVolume: Number(event.target.value) })}/></label><label>桌宠大小<input type="range" min="88" max="200" value={settings.petSize} onChange={(event) => save({ petSize: Number(event.target.value) })}/></label><label className="toggle-row"><span>开机启动</span><input type="checkbox" checked={settings.launchAtLogin} onChange={(event) => save({ launchAtLogin: event.target.checked })}/></label><div className="button-row"><button onClick={() => window.appApi.setPetVisible(false)}>暂时隐藏</button><button onClick={() => window.appApi.setPetVisible(true)}>显示桌宠</button></div></div></>}

      {tab === "appearance" && <><h1>外观</h1><div className="setting-card"><label>主题<select value={settings.theme} onChange={(event) => save({ theme: event.target.value as AppSettings["theme"] })}><option value="system">跟随系统</option><option value="light">日间</option><option value="dark">夜间</option></select></label><label className="toggle-row"><span>减少动画</span><input type="checkbox" checked={settings.reducedMotion} onChange={(event) => save({ reducedMotion: event.target.checked })}/></label></div></>}
      {status && <div className="toast" onClick={() => setStatus("")}>{status}</div>}
    </section>
  </main>;
}
